# Mises à jour automatiques des actions GitHub et des outils de développement.
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
